import fs from "node:fs/promises";
import path from "node:path";
import type { Job } from "../domain/job.js";
import type { ArticleRepository } from "../ports/articleRepository.js";
import type { JobRepository } from "../ports/jobRepository.js";
import { sha256 } from "../migration/articleInventory.js";
import { BuildService } from "./buildService.js";
import { canonicalStateHash, collectPublicArticles } from "./publicationPolicy.js";
import { IndexService } from "./indexService.js";
import { ReconciliationService } from "./reconciliationService.js";
import { ImageService } from "./imageService.js";
import { isArticleSource } from "../infrastructure/contentPaths.js";
import { canonicalizePath, resolveContentPath } from "../infrastructure/contentPaths.js";

export type DoctorSeverity = "INFO" | "WARNING" | "ERROR" | "CRITICAL";
export interface DoctorFinding { code: string; severity: DoctorSeverity; area: "identity" | "lifecycle" | "links" | "index" | "moc" | "build" | "runtime" | "images"; message: string; articleId?: string; path?: string; fixable: boolean; fixed: boolean; reviewRequired: boolean; }
export interface DoctorReport { generatedAt: string; healthy: boolean; fixed: number; findings: DoctorFinding[]; }

export class DoctorService {
  private readonly indexes: IndexService; private readonly buildService: BuildService; private readonly reconciliation: ReconciliationService; private readonly images: ImageService;
  constructor(private readonly vaultRoot: string, private readonly articles: ArticleRepository, private readonly jobs?: Pick<JobRepository<Job>, "all" | "get">) { this.indexes = new IndexService(vaultRoot, articles); this.buildService = new BuildService(vaultRoot, articles, this.indexes); this.reconciliation = new ReconciliationService(vaultRoot, articles, jobs); this.images = new ImageService(vaultRoot, articles); }

  async run(fix = false): Promise<DoctorReport> {
    const fixedFindings: DoctorFinding[] = [];
    if (fix) {
      const migrated = await this.images.migrate(false); for (const item of migrated.filter((entry) => entry.status === "migrated" || entry.status === "already_webp")) fixedFindings.push({ code: "IMAGE_METADATA_REFRESHED", severity: "INFO", area: "images", message: item.message, articleId: item.articleId, fixable: true, fixed: true, reviewRequired: false });
      const reconciled = await this.reconciliation.reconcileAll(true); for (const item of reconciled.findings.filter((entry) => entry.repaired)) fixedFindings.push({ code: item.code, severity: item.severity, area: "lifecycle", message: item.message, articleId: item.articleId, fixable: true, fixed: true, reviewRequired: false });
      try { await this.indexes.rebuildAll(); fixedFindings.push({ code: "DERIVED_INDEXES_REBUILT", severity: "INFO", area: "index", message: "Deterministic indexes and MOCs rebuilt", fixable: true, fixed: true, reviewRequired: false }); await this.buildService.build(); fixedFindings.push({ code: "DIST_REBUILT", severity: "INFO", area: "build", message: "Static dist rebuilt and validated", fixable: true, fixed: true, reviewRequired: false }); } catch (error) { fixedFindings.push({ code: "SAFE_FIX_BLOCKED", severity: "ERROR", area: "build", message: error instanceof Error ? error.message : String(error), fixable: false, fixed: false, reviewRequired: true }); }
    }
    const findings = [...fixedFindings, ...await this.inspect()]; findings.sort((a, b) => severityRank(b.severity) - severityRank(a.severity) || a.code.localeCompare(b.code) || (a.articleId ?? "").localeCompare(b.articleId ?? "")); return { generatedAt: new Date().toISOString(), healthy: !findings.some((finding) => !finding.fixed && ["ERROR", "CRITICAL"].includes(finding.severity)), fixed: findings.filter((finding) => finding.fixed).length, findings };
  }

  private async inspect(): Promise<DoctorFinding[]> {
    const findings: DoctorFinding[] = []; let metadata;
    try { metadata = await this.articles.list(); } catch (error) { return [{ code: "INVALID_METADATA_REGISTRY", severity: "CRITICAL", area: "identity", message: error instanceof Error ? error.message : String(error), fixable: false, fixed: false, reviewRequired: true }]; }
    const ids = new Set<string>(); const slugs = new Map<string, string>(); const paths = new Set<string>();
    for (const article of metadata) {
      if (ids.has(article.id)) findings.push(f("DUPLICATE_ID", "CRITICAL", "identity", `Duplicate ID ${article.id}`, false, true, article.id)); ids.add(article.id); const slug = article.slug.toLowerCase(); if (slugs.has(slug) && slugs.get(slug) !== article.id) findings.push(f("DUPLICATE_SLUG", "CRITICAL", "identity", `Duplicate slug ${article.slug}`, false, true, article.id)); else slugs.set(slug, article.id); paths.add(normalizePath(article.sourcePath));
      let source: string; try { source = await resolveContentPath(this.vaultRoot, article.sourcePath); } catch (error) { const code = String(error).includes("OUTSIDE") ? "UNSAFE_SOURCE_PATH" : String(error).includes("AMBIGUOUS") ? "AMBIGUOUS_SOURCE_PATH" : "MISSING_SOURCE"; findings.push(f(code, code === "MISSING_SOURCE" && article.status !== "published" ? "WARNING" : "ERROR", "identity", article.sourcePath, false, true, article.id)); source = ""; } if (source) { try { const body = await fs.readFile(source, "utf8"); if (!article.contentHash || sha256(body) !== article.contentHash) findings.push(f("SOURCE_HASH_MISMATCH", article.status === "published" ? "ERROR" : "WARNING", "identity", article.sourcePath, false, true, article.id)); for (const asset of referencedAssets(body)) { try { await resolveContentPath(this.vaultRoot, asset); } catch { findings.push(f("MISSING_REFERENCED_ASSET", "ERROR", "images", asset, false, true, article.id)); } } } catch { findings.push(f("MISSING_SOURCE", article.status === "published" ? "ERROR" : "WARNING", "identity", article.sourcePath, false, true, article.id)); } }
      const tombstone = await this.articles.getTombstone(article.id); if (article.status === "published" && tombstone) findings.push(f("PUBLISHED_TOMBSTONED", "CRITICAL", "lifecycle", "Published article has tombstone", false, true, article.id)); if (article.status === "deleted" && !tombstone) findings.push(f("DELETED_WITHOUT_TOMBSTONE", "CRITICAL", "lifecycle", "Deleted article has no tombstone", false, true, article.id)); if (article.status !== "deleted" && tombstone) findings.push(f("ACTIVE_WITH_TOMBSTONE", "CRITICAL", "lifecycle", "Active article has tombstone", false, true, article.id)); const revisions = await this.articles.history(article.id); if ((revisions.at(-1)?.revision ?? 0) !== article.currentRevision) findings.push(f("REVISION_COUNTER_MISMATCH", "ERROR", "lifecycle", `${article.currentRevision} != ${revisions.at(-1)?.revision ?? 0}`, true, false, article.id));
      if (article.image) { const image = safePath(this.vaultRoot, article.image.path); if (!image || !await exists(image)) findings.push(f("MISSING_IMAGE", "ERROR", "images", article.image.path, true, true, article.id)); const inspection = await this.images.inspect(article.image); if (inspection.issue) findings.push(f(`IMAGE_${inspection.issue.toUpperCase()}`, inspection.issue === "missing_alt" ? "WARNING" : "ERROR", "images", article.image.path, inspection.issue !== "missing_alt", true, article.id)); }
      else findings.push(f("MISSING_IMAGE_METADATA", "WARNING", "images", "No public image metadata", false, true, article.id));
    }
    for (const source of await listMarkdown(path.join(this.vaultRoot, "10_Published"))) { const relative = normalizePath(path.relative(this.vaultRoot, source)); if (isArticleSource(relative) && !paths.has(relative)) findings.push({ ...f("MISSING_METADATA", "WARNING", "identity", relative, false, true), path: relative }); }
    for (const tombstone of await this.articles.listTombstones()) if (!ids.has(tombstone.articleId)) findings.push(f("TOMBSTONE_WITHOUT_ARTICLE", "CRITICAL", "lifecycle", tombstone.articleId, false, true, tombstone.articleId));
    const events = await this.articles.events(); const terminal = new Set(events.filter((event) => ["completed", "failed"].includes(event.phase)).map((event) => event.operationId)); for (const event of events.filter((entry) => entry.phase === "started" && !terminal.has(entry.operationId))) findings.push(f("INTERRUPTED_OPERATION", "WARNING", "runtime", event.operationId, false, true, event.articleId));
    for (const article of metadata) { const revisions = await this.articles.history(article.id); for (const revision of revisions) if (!events.some((event) => event.operationId === revision.operationId && event.phase === "completed" && event.revision === revision.revision)) findings.push(f("AUDIT_HISTORY_INCOMPLETE", "WARNING", "lifecycle", `Revision ${revision.revision} has no matching completed event`, false, true, article.id)); for (const event of events.filter((entry) => entry.articleId === article.id && entry.phase === "completed" && entry.revision !== undefined)) if (!revisions.some((revision) => revision.operationId === event.operationId && revision.revision === event.revision)) findings.push(f("EVENT_REVISION_MISMATCH", "WARNING", "lifecycle", `Event ${event.operationId} has no matching revision`, false, true, article.id)); }
    const redirects = await this.articles.redirects(); for (const [from, redirect] of Object.entries(redirects)) { if (!ids.has(redirect.articleId)) findings.push(f("INVALID_REDIRECT", "ERROR", "links", `${from} -> missing ${redirect.articleId}`, false, true)); const seen = new Set<string>([from]); let next = redirect.to; while (redirects[next]) { if (seen.has(next)) { findings.push(f("REDIRECT_LOOP", "CRITICAL", "links", `Loop at ${next}`, false, true)); break; } seen.add(next); next = redirects[next].to; } }
    const { publicArticles } = await collectPublicArticles(this.vaultRoot, this.articles); const links = await this.indexes.analyzeLinks(publicArticles); for (const broken of links.broken) findings.push(f("BROKEN_INTERNAL_LINK", "ERROR", "links", `${broken.target} (${broken.reason})`, false, true, broken.sourceId));
    const stateHash = await canonicalStateHash(this.vaultRoot, this.articles); const manifest = await readJson<{ source_revision_hash?: string; indexes?: Record<string, string> }>(path.join(this.indexes.generatedDir, "index-manifest.json")); if (!manifest) findings.push(f("MISSING_INDEX", "ERROR", "index", "index-manifest.json missing", true, false)); else { if (manifest.source_revision_hash !== stateHash) findings.push(f("STALE_INDEX", "ERROR", "index", "Canonical state hash differs", true, false)); for (const [name, expected] of Object.entries(manifest.indexes ?? {})) { const file = name === "moc" ? undefined : path.join(this.indexes.generatedDir, `${name}.${name === "sitemap" ? "xml" : "json"}`); if (file && await exists(file) && sha256(await fs.readFile(file, "utf8")) !== expected) findings.push(f("INDEX_HASH_MISMATCH", "ERROR", "index", name, true, false)); } }
    const search = await readJson<Array<{ id: string }>>(path.join(this.indexes.generatedDir, "search-index.json")); const publicIds = new Set(publicArticles.map((article) => article.metadata.id)); if (search) for (const entry of search) if (!publicIds.has(entry.id)) findings.push(f("PRIVATE_ARTICLE_INDEXED", "CRITICAL", "index", entry.id, true, false, entry.id));
    const allowedGenerated = new Set(["search-index.json", "category-index.json", "related.json", "backlink-index.json", "sitemap.xml", "index-manifest.json"]); for (const entry of await fs.readdir(this.indexes.generatedDir, { withFileTypes: true }).catch(() => [])) if (!(entry.isDirectory() && entry.name === "moc") && !(entry.isFile() && allowedGenerated.has(entry.name))) findings.push({ ...f("ORPHAN_GENERATED_ARTIFACT", "WARNING", "index", entry.name, true, false), path: path.join("generated", entry.name) });
    const mocDir = path.join(this.indexes.generatedDir, "moc"); if (!await exists(mocDir)) findings.push(f("MISSING_MOC", "ERROR", "moc", "generated/moc missing", true, false)); else { const mocText = (await Promise.all((await listFiles(mocDir)).map((file) => fs.readFile(file, "utf8")))).join("\n"); for (const id of publicIds) { const count = [...mocText.matchAll(new RegExp(`<!--\\s*${escapeRegExp(id)}\\s*-->`, "g"))].length; if (count === 0) findings.push(f("PUBLIC_ARTICLE_MISSING_FROM_MOC", "ERROR", "moc", id, true, false, id)); if (count > 1) findings.push(f("DUPLICATE_MOC_ENTRY", "ERROR", "moc", id, true, false, id)); } for (const match of mocText.matchAll(/<!--\s*(art_[A-Za-z0-9._-]+)\s*-->/g)) if (!publicIds.has(match[1])) findings.push(f("PRIVATE_ARTICLE_IN_MOC", "CRITICAL", "moc", match[1], true, false, match[1])); }
    try { await this.buildService.validate(); } catch (error) { findings.push(f("DIST_INVALID_OR_STALE", "WARNING", "build", error instanceof Error ? error.message : String(error), true, true)); }
    for (const job of await this.jobs?.all() ?? []) {
      if (["failed", "failed_review_required"].includes(job.status) && job.worktreePath) findings.push(f("FAILED_JOB_RESIDUE", "WARNING", "runtime", `${job.id}: ${job.worktreePath}`, false, true));
      if (["running", "waiting_publish", "publishing"].includes(job.status)) findings.push(f("INTERRUPTED_JOB", "ERROR", "runtime", `${job.id}: ${job.status}`, false, true));
      if (["failed", "failed_review_required", "cancelled"].includes(job.status) && job.article) {
        const article = metadata.find((item) => item.id === job.article!.articleId);
        const publishedPath = normalizePath(job.article.sourcePath).startsWith("10_published/");
        if (publishedPath && (!article || article.status !== "published")) findings.push(f("FAILED_JOB_PUBLISHED_RESIDUE", "CRITICAL", "runtime", `${job.id}: ${job.article.sourcePath}`, false, true, job.article.articleId));
      }
    }
    return findings;
  }
}

function f(code: string, severity: DoctorSeverity, area: DoctorFinding["area"], message: string, fixable: boolean, reviewRequired: boolean, articleId?: string): DoctorFinding { return { code, severity, area, message, articleId, fixable, fixed: false, reviewRequired }; }
function severityRank(value: DoctorSeverity): number { return { INFO: 0, WARNING: 1, ERROR: 2, CRITICAL: 3 }[value]; }
function normalizePath(value: string): string { return canonicalizePath(value).toLowerCase(); }
function safePath(root: string, relative: string): string | undefined { const base = path.resolve(root); const target = path.resolve(base, relative.replace(/[\\/]/g, path.sep)); return target === base || target.startsWith(`${base}${path.sep}`) ? target : undefined; }
async function exists(file: string): Promise<boolean> { return fs.access(file).then(() => true).catch(() => false); }
async function readJson<T>(file: string): Promise<T | undefined> { try { return JSON.parse(await fs.readFile(file, "utf8")) as T; } catch (error) { if ((error as NodeJS.ErrnoException).code === "ENOENT") return undefined; throw error; } }
async function listMarkdown(dir: string): Promise<string[]> { try { const result: string[] = []; for (const entry of await fs.readdir(dir, { withFileTypes: true })) { const target = path.join(dir, entry.name); if (entry.isDirectory()) result.push(...await listMarkdown(target)); else if (entry.name.toLowerCase().endsWith(".md")) result.push(target); } return result; } catch { return []; } }
async function listFiles(dir: string): Promise<string[]> { try { const result: string[] = []; for (const entry of await fs.readdir(dir, { withFileTypes: true })) { const target = path.join(dir, entry.name); if (entry.isDirectory()) result.push(...await listFiles(target)); else result.push(target); } return result; } catch { return []; } }
function escapeRegExp(value: string): string { return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&"); }
function referencedAssets(body: string): string[] { return [...new Set([...body.matchAll(/(?:!\[\[[^\]]*\]\]|(?:infographic_path|image_path):\s*["']?)(50_Assets\/[^\s"'\]\)]+)/gi)].map((match) => match[1].replace(/\\/g, "/")))]; }
